name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Create bin directory
      run: mkdir -p bin

    - name: Go Cache
      uses: actions/cache@v4
      id: go-cache
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Debug Cache
      if: failure() && steps.go-cache.outcome == 'failure'
      run: |
        ls -la ~/.cache || true
        ls -la ~/go/pkg || true
        echo "Cache directories may not exist yet, continuing with build"

    - name: Build Linux Binary
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o bin/go-parse-linux-amd64 ./cmd
    
    - name: Build MacOS Binary
      run: |
        GOOS=darwin GOARCH=amd64 go build -v -o bin/go-parse-darwin-amd64 ./cmd
    
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: go-parse-linux-amd64
        path: bin/go-parse-linux-amd64
    
    - name: Upload MacOS Binary
      uses: actions/upload-artifact@v4
      with:
        name: go-parse-darwin-amd64
        path: bin/go-parse-darwin-amd64

    - name: Test
      run: go test -v ./...
