name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Binary
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true
    
    - name: Build Linux Binary
      run: |
        GOOS=linux GOARCH=amd64 go build -v -o bin/go-parse-linux-amd64 ./cmd
    
    - name: Build MacOS Binary
      run: |
        GOOS=darwin GOARCH=amd64 go build -v -o bin/go-parse-darwin-amd64 ./cmd
    
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: go-parse-linux-amd64
        path: bin/go-parse-linux-amd64
    
    - name: Upload MacOS Binary
      uses: actions/upload-artifact@v4
      with:
        name: go-parse-darwin-amd64
        path: bin/go-parse-darwin-amd64

    - name: Test
      run: go test -v ./...
